# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: <Your Name> Portfolio
email: you@email.com
description: >- # this means to ignore newlines until "baseurl:"
  A description of you that you would want to see as the summary if an employer
  searched for your name and this popped up as the first result.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins: jekyll-feed
# Do not minify SASS
sass:
  style: full

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


collections:
  # Professional Sills will be computer programs, programming languages, tools of
  # the trade.  For Programmers examples might be Ruby, C#, Git, Docker, etc.
  # For a consice, elegent display, 5 or 6 entries are recommended.
  # Skills are to be ranked out of 5.
  ProfessionalSkills:
    HTML: 3
    C#: 4
    Visual Basic: 4
    JavaScript: 4
    Synergex DBL: 5

  # Personal Talents will be aspects of yourself that would translate into any career
  # field:  Leadership, Critical Thinking, Problem Solving, Tenacity, etc.
  # For a consice, elegent display, 5 or 6 entries are recommended.
  # Talents are to be ranked out of 5.
  PersonalTalents:
    Leadership: 3
    Learning: 4
    Critical Thinking: 5
    Problem Solving: 5

# Social Media Links
website: www.yoursite.com
twitter: you-at-twitter
facebook: your-facebook-page
googlePlus: your-googleplus-link
stackOverflow: your-stackoverflow-profile
github: your-github-username
linkedin: your-linkedin-profile-utl
